name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - git-workflow-docs

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - uses: actions/checkout@v2
      - name: Prepare system
        run: sudo apt install graphviz
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./doc/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: docs