name: 'Release on approved PR'

on:
  pull_request:
    types:
      - closed
jobs:
  buildOnUbuntuX64:
    runs-on: ubuntu-latest
    name: Build on ubuntu:latest-x64
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.3
        id: install-boost
        with:
          boost_version: 1.83.0
          platform_version: 22.04
          link: static+shared
      - name: Prepare system
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install -y libspdlog-dev g++-13
          export PATH=$PATH:${{steps.install-boost.outputs.BOOST_ROOT}}/lib
          export LD_LIBRARY_PATH=${{steps.install-boost.outputs.BOOST_ROOT}}/lib
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13 3 ${{steps.install-boost.outputs.BOOST_ROOT}}/include ${{steps.install-boost.outputs.BOOST_ROOT}}/lib ${{ steps.install-boost.outputs.BOOST_ROOT }}
          cd build
          ./test
      - name: Build executable
        run: |
          ./build.sh ${{ github.run_number }} Release OFF ON protei_cov protei_cov-0.0.${{ github.run_number }}-ubuntu22.04-x64 /usr/bin/g++-13 3 ${{steps.install-boost.outputs.BOOST_ROOT}}/include ${{steps.install-boost.outputs.BOOST_ROOT}}/lib ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Test run executable
        run: |
          sudo chmod +x build/protei_cov
          cd build
          ./protei_cov test
      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: build/protei_cov-0.0.${{ github.run_number }}-ubuntu22.04-x64.zip
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          token: ${{ secrets.ACTION_TOKEN }}

  buildOnUbuntuArm64:
    runs-on: [self-hosted, linux, ARM64]
    name: Build on ubuntu22.04-aarch64
    environment: env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13 5
          cd build
          ./test
      - name: Build executable
        run: |
          ./build.sh ${{ github.run_number }} Release OFF ON protei_cov protei_cov-0.0.${{ github.run_number }}-ubuntu22.04-arm64 /usr/bin/g++-13 5
      - name: Test run executable
        run: |
          sudo chmod +x build/protei_cov
          cd build
          ./protei_cov test
      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: build/protei_cov-0.0.${{ github.run_number }}-ubuntu22.04-arm64.zip
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          token: ${{ secrets.ACTION_TOKEN }}

