name: 'C++ tests without release'

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Prepare system
        run: |
          sudo apt update && sudo apt install -y libspdlog-dev libboost-all-dev
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test 
          cd build
          ./test