name: 'C++ tests without release'

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Prepare system
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install -y libspdlog-dev libboost-all-dev g++-13
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13
          cd build
          echo "======================"
          ls
          echo "======================"
          ./test

  testsOnAarch64:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Prepare system
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install -y libspdlog-dev libboost-all-dev g++-13
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13
          cd build
          echo "======================"
          ls
          echo "======================"
          ./test
