name: 'C++ tests without release'

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.3
        id: install-boost
        with:
          boost_version: 1.83.0
          platform_version: 22.04
          link: static+shared
      - name: Prepare system
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install -y libspdlog-dev g++-13
          export PATH=$PATH:${{steps.install-boost.outputs.BOOST_ROOT}}/lib
          export LD_LIBRARY_PATH=${{steps.install-boost.outputs.BOOST_ROOT}}/lib
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13 \ 
          ${{steps.install-boost.outputs.BOOST_ROOT}}/include ${{steps.install-boost.outputs.BOOST_ROOT}}/lib \ 
          ${{ steps.install-boost.outputs.BOOST_ROOT }}
          cd build
          ./test

  testsOnAarch64:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Test
        run: |
          ./build.sh ${{ github.run_number }} Debug ON ON test test /usr/bin/g++-13
          cd build
          ./test
